### ISSUE TITLE
Pi-Apps credit

### ISSUE THREAD

**Issue by Botspot** [piware14/pi-ware#10]
If your repository [uses Pi-Apps code](https://github.com/zachthecoder14/pi-ware/blob/main/apps/ATLauncher/install), I think it's only fair to give Pi-Apps credit.

**Comment by Painadath** [comment]
sure @Botspot We are Truely insipired of you and also where to give credits in the README.md or the scripts start or the scripts repo

**Comment by Itai-Nelken** [comment]
According to the license pi-apps uses, you should add this to the top of any script from pi-apps.
```
this code is taken from/based on pi-apps code.
    Copyright (C) 2021  Botspot

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

**Comment by Painadath** [comment]
will do but our pi-ware is using MIT license

**Comment by ghost** [comment]
> If your repository [uses Pi-Apps code](https://github.com/zachthecoder14/pi-ware/blob/main/apps/ATLauncher/install), I think it's only fair to give Pi-Apps credit.

Will do, would it be possible for Pi-Ware to be added to Pi Apps in the future? Or is that asking too much?

**Comment by Itai-Nelken** [comment]
>will do but our pi-ware is using MIT license

maybe something like this:
```
this code is taken from/based on pi-apps code that is licensed under the GPL3 license:
    Copyright (C) 2021  Botspot

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

**Comment by Painadath** [comment]
ok

**Comment by Botspot** [comment]
> Will do, would it be possible for Pi-Ware to be added to Pi Apps in the future? Or is that asking too much?

I have tried your app store. Currently it doesn't behave "finished" or "complete". It seems rough around the edges, and I think the lack of apps may hinder it from attracting users.
Specifically, it won't work on any systems that have a different username. Also, if anything goes wrong, Pi-Ware won't notify the user or stop the script.

If Pi-Ware proves itself to be well-made, well-maintained, easy to use, attractive to many users, unique (not like PiGro, PiKISS or Pi-Apps), system-independent, arch-independent, and otherwise appropriate to add, I'd be fine with it being added to Pi-Apps.

**Comment by oxmc** [comment]
> > Will do, would it be possible for Pi-Ware to be added to Pi Apps in the future? Or is that asking too much?
> 
> I have tried your app store. Currently it doesn't behave "finished" or "complete". It seems rough around the edges, and I think the lack of apps may hinder it from attracting users.
> Specifically, it won't work on any systems that have a different username. Also, if anything goes wrong, Pi-Ware won't notify the user or stop the script.
> 
> If Pi-Ware proves itself to be well-made, well-maintained, easy to use, attractive to many users, unique (not like PiGro, PiKISS or Pi-Apps), system-independent, arch-independent, and otherwise appropriate to add, I'd be fine with it being added to Pi-Apps.

Alright.

**Comment by Painadath** [comment]
@Botspot @Itai-Nelken i have added credits in atlauncher install and uninstall
if there is no problem can i close this issue?

**Comment by ghost** [comment]
> > Will do, would it be possible for Pi-Ware to be added to Pi Apps in the future? Or is that asking too much?
> 
> I have tried your app store. Currently it doesn't behave "finished" or "complete". It seems rough around the edges, and I think the lack of apps may hinder it from attracting users.
> Specifically, it won't work on any systems that have a different username. Also, if anything goes wrong, Pi-Ware won't notify the user or stop the script.
> 
> If Pi-Ware proves itself to be well-made, well-maintained, easy to use, attractive to many users, unique (not like PiGro, PiKISS or Pi-Apps), system-independent, arch-independent, and otherwise appropriate to add, I'd be fine with it being added to Pi-Apps.

Alvarito is currently rewriting some things that make Pi-Ware easier to use. This includes using it from any username. We will definitely work on notifying the user on any problems that are going on. We are a new App Store so we don’t have much yet.

**Comment by Itai-Nelken** [comment]
> @Botspot @Itai-Nelken i have added credits in atlauncher install and uninstall
> if there is no problem can i close this issue?

I can't see the changes, in what commit did you add them?

**Comment by Painadath** [comment]
> > @Botspot @Itai-Nelken i have added credits in atlauncher install and uninstall
> > if there is no problem can i close this issue?
> 
> I can't see the changes, in what commit did you add them?

look at the pi-ware bash script repo and also whcih is the file that us taken from pi-apps
atlauncher install and uninstall is made by rpi-coder

**Comment by ghost** [comment]
> > > @Botspot @Itai-Nelken i have added credits in atlauncher install and uninstall
> > > if there is no problem can i close this issue?
> > 
> > 
> > I can't see the changes, in what commit did you add them?
> 
> look at the pi-ware bash script repo and also whcih is the file that us taken from pi-apps
> atlauncher install and uninstall is made by rpi-coder

Sorry I got the credits wrong this is where I got the ATLauncher files from here: https://github.com/pi-dev500/MinecraftMicrosoftPILauncher
It was rpi-dev500, not rpi-coder, my bad.

**Comment by torralbaa** [comment]
Wait uh, if the ATLauncher install script is licensed under the GPL, we _can't_ include it in a MIT-licensed project. These two are incompatible in that way.

**Comment by ghost** [comment]
> Wait uh, if the ATLauncher install script is licensed under the GPL, we _can't_ include it in a MIT-licensed project. These two are incompatible in that way.

I don’t see a license:
https://github.com/pi-dev500/MinecraftMicrosoftPILauncher

**Comment by ghost** [comment]
> If your repository [uses Pi-Apps code](https://github.com/zachthecoder14/pi-ware/blob/main/apps/ATLauncher/install), I think it's only fair to give Pi-Apps credit.

We don’t use Pi Apps code, we just want to make Pi Apps installable from Pi Ware.

**Comment by Botspot** [comment]
> We don’t use Pi Apps code, we just want to make Pi Apps installable from Pi Ware.

Unless I'm mistaken, Pi Ware is making use of scripts that were originally designed and intended for Pi-Apps.
With that in mind, wouldn't it be appropriate to mention Pi-Apps somewhere as beneficial to the development of Pi Ware?

**Comment by ghost** [comment]
> > We don’t use Pi Apps code, we just want to make Pi Apps installable from Pi Ware.
> 
> Unless I'm mistaken, Pi Ware is making use of scripts that were originally designed and intended for Pi-Apps.
> With that in mind, wouldn't it be appropriate to mention Pi-Apps somewhere as beneficial to the development of Pi Ware?

I’m not aware of us taking any Pi Apps code. We just want to simply make it possible to install Pi Apps from the Pi-Ware App Store.

**Comment by Painadath** [comment]
> > > We don’t use Pi Apps code, we just want to make Pi Apps installable from Pi Ware.
> > 
> > 
> > Unless I'm mistaken, Pi Ware is making use of scripts that were originally designed and intended for Pi-Apps.
> > With that in mind, wouldn't it be appropriate to mention Pi-Apps somewhere as beneficial to the development of Pi Ware?
> 
> I’m not aware of us taking any Pi Apps code. We just want to simply make it possible to install Pi Apps from the Pi-Ware App Store.

nope @Botspot told that we are using ATLauncher script which was made for pi-apps
i think we should add this in the readme.md 
```
inspired from Botspot's pi-apps
```
it is enough @Botspot

**Comment by Botspot** [comment]
> i think we should add this in the readme.md
> ```
> inspired from Botspot's pi-apps
> ```
> it is enough @Botspot

That doesn't give the impression that Pi Ware is directly benefiting from Pi-Apps by using scripts that were intended for Pi-Apps.
How about this:
```
Pi Ware benefits from scripts that were originally developed for Pi-Apps.
```

**Comment by Painadath** [comment]
nope so we will remove ATlauncher soon as when using the line @Botspot mensioned above can make users think that pi-ware is depending on pi-apps

**Comment by Painadath** [comment]
@Botspot i have removed Atlauncher from pi-ware
so can you close this issue
https://github.com/zachthecoder14/pi-ware/commit/572614e187839c31d878f56251f1f04aed8daf7d
