### ISSUE TITLE
Lunar Client

### ISSUE THREAD

**Issue by ghost** [piware14/pi-ware#13]
Hey guys, @gl91306 was able to compile Lunar Client for the Raspberry Pi. However, we need testers.

**Comment by ghost** [comment]
Hello there, Lunar Client has been added to Pi Ware. I’m closing this issue now, please make a new issue if there are any bugs.

**Comment by ryanfortner** [comment]
How did you compile it?

**Comment by ghost** [comment]
> How did you compile it?

Ask PiKAT on the Discord server, he did it.

**Comment by Painadath** [comment]
I think this issue must be reopened and remove lunar client temporarily from pi-ware because it is not is not ready yet

**Comment by NoozAbooz** [comment]
Does lunar client even have arm lwjgl libraries?

**Comment by Painadath** [comment]
> Does lunar client even have arm lwjgl libraries?

No it uses seperate lwgl libraries I think

**Comment by oxmc** [comment]
Since this is fixed now, i am closing this issue.
