### ISSUE TITLE
Bad idea with firefox

### ISSUE THREAD

**Issue by CleanMachine1** [piware14/pi-ware#17]
https://github.com/zachthecoder14/pi-ware/blob/main/apps/Firefox/install

You shouldn't add an entire ubuntu repo, this will cause overlapping issues, if you are going to add it, make sure to give it lower priority

**Comment by Painadath** [comment]
> https://github.com/zachthecoder14/pi-ware/blob/main/apps/Firefox/install
> 
> You shouldn't add an entire ubuntu repo, this will cause overlapping issues, if you are going to add it, make sure to give it lower priority

@CleanMachine1 I don't think so I installed it but removed no error and also can you figure out how to add a scroll bar to pi-ware if so contact us on discord

**Comment by CleanMachine1** [comment]
You wont get issues immediately. 
However debian wont like merging packages, eg if the audio manager gets an update, audio may fully break

**Comment by ghost** [comment]
> https://github.com/zachthecoder14/pi-ware/blob/main/apps/Firefox/install
> 
> You shouldn't add an entire ubuntu repo, this will cause overlapping issues, if you are going to add it, make sure to give it lower priority

It seems to work fine.

**Comment by CleanMachine1** [comment]
Until it doesn't. Learn how to give apt repos lower priority otherwise people will be complaining when things break, which will happen, trust me

**Comment by ghost** [comment]
> Until it doesn't. Learn how to give apt repos lower priority otherwise people will be complaining when things break, which will happen, trust me

Here, let me update the scripts.

**Comment by ghost** [comment]
> > Until it doesn't. Learn how to give apt repos lower priority otherwise people will be complaining when things break, which will happen, trust me
> 
> Here, let me update the scripts.

Never mind, there’s nothing to update. Ask @chunky-milk. He provided the scripts.

**Comment by CleanMachine1** [comment]
We'll wait for his input on it

**Comment by ryanfortner** [comment]
> You shouldn't add an entire ubuntu repo, this will cause overlapping issues, if you are going to add it, make sure to give it lower priority

![image](https://user-images.githubusercontent.com/71036629/119263102-b37c4680-bbab-11eb-89dd-4c6dce357a1e.png)

This part of the script will ensure that the `99bionic-updates` file is downloaded and placed in the correct place so that APT won't default to the Ubuntu repositories, it will be at a lower priority.

I've opened a PR to change the link of where the file is hosted, because 1.) The original link was broken on my end, and 2.) Some people may not want the Pi-Ware scripts to be pinging bit.ly servers, so I changed the link to git.io, a link shortening service run by GitHub.

**Comment by ghost** [comment]
Ok guys, I merged. @CleanMachine1, any further issues?

**Comment by CleanMachine1** [comment]
great work!

**Comment by ghost** [comment]
Also, @CleanMachine1, would you like to help out with Pi-Ware? We have some bugs that need fixing.

**Comment by CleanMachine1** [comment]
What have you got, sure

**Comment by CleanMachine1** [comment]
I am very busy often at tldr-pages however send me a ping and i'll get to you

**Comment by CleanMachine1** [comment]
Fixed with #18

**Comment by CleanMachine1** [comment]
Feel free to contact me at gitter

**Comment by ghost** [comment]
Is there any way I can contact you?

**Comment by ghost** [comment]
We currently need help detecting the user’ Pi’s username, because /home/pi won’t work for everybody. We also need a scroll bar so users can view all the apps.

**Comment by CleanMachine1** [comment]
I might be able to help with the pi stuff however I am not a GUI designer!

**Comment by ghost** [comment]
> I might be able to help with the pi stuff however I am not a GUI designer!

We’re using tkinter and the basic GUI is already made, we just need a scroll bar.

**Comment by ghost** [comment]
Let me do some updates first.

**Comment by ghost** [comment]
Done.

**Comment by ghost** [comment]
Now you can start with detecting the username of the Pi that Pi-Ware is being used on. I’ll make a new issue.

**Comment by ghost** [comment]
I made the issue (#19). Go ahead and check that out.
