### ISSUE TITLE
Detect the username of the user’s OS

### ISSUE THREAD

**Issue by ghost** [piware14/pi-ware#19]
@CleanMachine1 we can talk here now.

**Comment by CleanMachine1** [comment]
What files need to be done?
The python code could be done pretty easy 

https://github.com/CleanMachine1/Python-Code/blob/main/GettingUser.py

I published that and that entire repo for others to learn from.

Give me a list of files to change, what happens if this is run as root?

**Comment by ghost** [comment]
We’ll store.py is the main code. You’ll

> What files need to be done?
> The python code could be done pretty easy
> 
> https://github.com/CleanMachine1/Python-Code/blob/main/GettingUser.py
> 
> I published that and that entire repo for others to learn from.
> 
> Give me a list of files to change, what happens if this is run as root?

Go ahead and install Pi-Ware. The main file is store.py. The app is found in Menu > Accessories. In store.py you’ll see /home/pi referenced in there a few times. We need to find out the user’s username because not everyone has the username of pi.

**Comment by ghost** [comment]
I actually already discovered the get pass trick a week or two ago. I’m just not sure how to incorporate it.

**Comment by ghost** [comment]
Also, when you install Pi-Ware the icon won’t appear on the desktop until the next boot, so just reboot.

**Comment by ghost** [comment]
Hey, I got it. Pi-Ware now detects the username of the OS that is being used.
