### ISSUE TITLE
Remove Discord

### ISSUE THREAD

**Issue by BurntRouter** [piware14/pi-ware#2]
Remove the Discord App as it uses a 3rd party client which is strictly against Discord's Terms of Service and could result in users getting banned.

**Comment by Painadath** [comment]
Hey @BurntRouter discord is also in the pi-apps why are you hunting just pi-ware

**Comment by Painadath** [comment]
and also it is not maked by us

**Comment by gl91306** [comment]
> Remove the Discord App as it uses a 3rd party client which is strictly against Discord's Terms of Service and could result in users getting banned.

bruh dude its an electron app thats linked to the official diescord site
