### ISSUE TITLE
DollarSkip

### ISSUE THREAD

**Issue by CleanMachine1** [piware14/pi-ware#22]
Might wanna take a look at my dollarskip repo, not a software however feel free to add it if you want, just let me check the files and give me credit for the software

Up to you

**Comment by ghost** [comment]
Why not? Just make a zip with an “install” file, an “uninstall” file, an icon png file and a description text file.

**Comment by CleanMachine1** [comment]
Actually after looking whats currently hear again, dollarskip doesn't fit

**Comment by CleanMachine1** [comment]
Also I thought about it a little more and would rather a user view my repo rather than here.

**Comment by ghost** [comment]
> Also I thought about it a little more and would rather a user view my repo rather than here.

Alright then, if you would like any features/apps to be added just open an issue.

**Comment by CleanMachine1** [comment]
Im not a Linux Pi user, so I don't really want the features, but perfectly happy to suggest them if I think of any.
I personally stick to X86 Ubuntu based or Arch

**Comment by ghost** [comment]
> Im not a Linux Pi user, so I don't really want the features, but perfectly happy to suggest them if I think of any.
> I personally stick to X86 Ubuntu based or Arch

Then you can suggest an app if you want. Maybe aptcleaner? I heard you helped make it.

**Comment by CleanMachine1** [comment]
How about bleachbit auto?

**Comment by ghost** [comment]
> How about bleachbit auto?

Make a new issue.
