### ISSUE TITLE
Maybe a bleachbit script to automatically clean

### ISSUE THREAD

**Issue by CleanMachine1** [piware14/pi-ware#23]
Bleachbit can delete files from a computer easily, its made to remove junk.

Its a pretty dangerous tool if you select stupid options.

**Comment by ghost** [comment]
> Bleachbit can delete files from a computer easily, its made to remove junk.
> 
> Its a pretty dangerous tool if you select stupid options.

Doesn’t this have the same purpose as aptcleaner?

**Comment by CleanMachine1** [comment]
No.
Please look into things.

https://duckduckgo.com/?q=bleachbit

There

**Comment by ghost** [comment]
Alright, where are the install/uninstall files?

**Comment by CleanMachine1** [comment]
sudo apt install bleachbit

sudo apt purge bleachbit

I didn't sign up to make them, just giving you some suggestions

**Comment by CleanMachine1** [comment]
Sorry that was rude of me.

**Comment by CleanMachine1** [comment]
bleachbit --list may be of some use

**Comment by ghost** [comment]
> sudo apt install bleachbit
> 
> sudo apt purge bleachbit
> 
> I didn't sign up to make them, just giving you some suggestions

If it’s already installable with sudo apt-get install, why do you want it on Pi-Ware?

**Comment by CleanMachine1** [comment]
Because it might be better to have a script that automates it

**Comment by ghost** [comment]
> Because it might be better to have a script that automates it

Ok, if you make one I will add it to Pi-Ware.

**Comment by CleanMachine1** [comment]
Give me a few days and i'll look into it

**Comment by ryanfortner** [comment]
> Its a pretty dangerous tool if you select stupid options.

Yes, this is unfortunately true... I bricked an OS installation once by selecting all the clean options in BleachBit

**Comment by ryanfortner** [comment]
> Yes, this is unfortunately true... I bricked an OS installation once by selecting all the cleaning options in BleachBit

**Comment by ghost** [comment]
> Give me a few days and i'll look into it

Ok, I’ll check back on the 31st.

**Comment by CleanMachine1** [comment]
Actually, I am not going to keep you waiting. I am very busy so I cannot promise anything, feel free to close if you want or make it on your own

**Comment by ghost** [comment]
> Actually, I am not going to keep you waiting. I am very busy so I cannot promise anything, feel free to close if you want or make it on your own

Ok, when or if you have any files ready, just comment here and I’ll re-open the issue.
