### ISSUE TITLE
APT Cleaner

### ISSUE THREAD

**Issue by ghost** [piware14/pi-ware#25]
Is this app installable with `sudo apt install`?
No, installing APT Cleaner requires the installer.
https://github.com/GabeCoder/aptcleaner

**Comment by ghost** [comment]
Hey there, I’ll check it out as soon as possible. Your app will be added to Pi-Ware.

**Comment by oxmc** [comment]
@GabeCoder,
To add this app to ``pi-ware``, you need to have 3 core files,

1. ``description.txt``
   -Containing the app's description,
   -a website(can be the GitHub repo),
   -And the app author(you).
2. ``install`` (no extension)
   -If your app installs any dependencies add the following line to your script,
  ```
   export PW_PREFIX="$HOME/.local/share/pi-ware"
   PACMANG="$(cat $PW_PREFIX/inst-pref)"
  ```
  and to install a package run,
  ``sudo $PACKMANG packagename``.
3. uninstall
   -As stated before, if your app installs any dependencies you have to add the following line to your script,
  ```
    export PW_PREFIX="$HOME/.local/share/pi-ware"
    PACMANG="$(cat $PW_PREFIX/inst-pref)"
  ```
   then to uninstall a package run,
   ``sudo $PACKMANG packagename``

**Comment by oxmc** [comment]
@GabeCoder I will make the install and uninstall scripts for your app.

**Comment by oxmc** [comment]
@GabeCoder This app has been added to pi-ware.
