### ISSUE TITLE
Deltarune

### ISSUE THREAD

**Issue by gl91306** [piware14/pi-ware#26]
Is this app installable with `sudo apt install`?
no
If you've created a zip file for this app, upload it here.
i havent created a zip for the app, but heres he installation and uninstallations scrpits

install:
echo Installing Deltarune...
git clone https://github.com/gl91306/deltarune.git
cd deltarune
cd Deltarune
chmod +x runner
./runner
touch $HOME/.local/share/applications/Deltarune.desktop
echo "[Desktop Entry]
Name=Deltarune
Comment="The sequel to Toby Fox's Undertale"
Exec=$HOME/deltarune/Deltarune/runner
Icon=$HOME/deltarune/Deltarune/deltarune.png
Categories=Game;
Type=Application
Terminal=false" > $HOME/.local/share/applications/Deltarune.desktop

uninstall:
rm -rf $HOME/deltarune
rm-rf $HOME/.local/share/applications/Deltarune.desktop
echo Deltarune has been uninstalled

**Comment by oxmc** [comment]
@gl91306 Please add a ```description.txt```.

**Comment by gl91306** [comment]
k
Deltarune, natively ported for the Raspberry Pi
Website: https://www.deltarune.com/
Credit to @Kneesnap for porting this to the pi3. Also thanks to @gl91306 for porting the pi4 runner to this game.

**Comment by ghost** [comment]
> Is this app installable with `sudo apt install`?
> no
> If you've created a zip file for this app, upload it here.
> i havent created a zip for the app, but heres he installation and uninstallations scrpits
> 
> install:
> echo Installing Deltarune...
> git clone https://github.com/gl91306/deltarune.git
> cd deltarune
> cd Deltarune
> chmod +x runner
> ./runner
> touch $HOME/.local/share/applications/Deltarune.desktop
> echo "[Desktop Entry]
> Name=Deltarune
> Comment="The sequel to Toby Fox's Undertale"
> Exec=$HOME/deltarune/Deltarune/runner
> Icon=$HOME/deltarune/Deltarune/deltarune.png
> Categories=Game;
> Type=Application
> Terminal=false" > $HOME/.local/share/applications/Deltarune.desktop
> 
> uninstall:
> rm -rf $HOME/deltarune
> rm-rf $HOME/.local/share/applications/Deltarune.desktop
> echo Deltarune has been uninstalled

This installs the version for pi4. What about pi3 users? Should we make an input that asks what pi you have?

**Comment by gl91306** [comment]
no its not only for pi 4 users, its for people using the fake kms driver, which is avilable for pi 4 and 3

**Comment by ghost** [comment]
> no its not only for pi 4 users, its for people using the fake kms driver, which is avilable for pi 4 and 3

What about full kms?

**Comment by oxmc** [comment]
> no its not only for pi 4 users, its for people using the fake kms driver, which is avilable for pi 4 and 3

As @zachthecoder14 stated before
>This installs the version for pi4. What about pi3 users? Should we make an input that asks what pi you have?

Do we need a prompt? or will it detect the system automaticly?

**Comment by gl91306** [comment]
it should work for everything exept legacy, which no-one uses anymore

**Comment by IsaacMvmv** [comment]
Ill see in my rpi 4

**Comment by IsaacMvmv** [comment]
Dont work with my aarch64 os, so nothing of me

**Comment by gl91306** [comment]
well the runner is meant to work for armvl

**Comment by IsaacMvmv** [comment]
Yes, but cant compile also for aarch64? Many people uses aarch64 becouse its faster than armhf

**Comment by oxmc** [comment]
True, but pi-ware was targeted for rpios at the moment.
And rpios is armv7l

**Comment by gl91306** [comment]
also how doesnt it work on aarch64? whats the error

**Comment by IsaacMvmv** [comment]
Yes, but they are trying to expand their support minimum to pacman package manager I think

**Comment by IsaacMvmv** [comment]
How? You want to open a different architecture executable, so, or qemu, or error

**Comment by gl91306** [comment]
i didnt really get what the last comment meant but im just asking, what error do you get in the terminal that makes it not run on  aarch64

**Comment by IsaacMvmv** [comment]
Cannot execute: Incorrect executable format

**Comment by gl91306** [comment]
ok ill try and find a arm64 runner for the pi

**Comment by IsaacMvmv** [comment]
But where did you find the files then?
I thought you have compiled it youself

**Comment by gl91306** [comment]
i got the armvl (not lecacy driver) runner from one of pitsebs pandora repos for deltarune. It allowed my to run any gms linux game by replacing the current runner with this one

**Comment by oxmc** [comment]
I have added Deltarune to pi-ware, I am now closing this issue.
