### ISSUE TITLE
Mari0

### ISSUE THREAD

**Issue by IsaacMvmv** [piware14/pi-ware#27]
Is this app installable with `sudo apt install`?
No
If you've created a zip file for this app, upload it here.
[Mari0-1.zip](https://github.com/zachthecoder14/pi-ware/files/6552947/Mari0-1.zip)

**Comment by oxmc** [comment]
@IsaacMvmv Thank you for submitting an app, please wait while we test it before adding it to pi-ware.

**Comment by zachthecoder14** [comment]
*pi-ware

**Comment by oxmc** [comment]
yes



That... sorry.

**Comment by Painadath** [comment]
As mario is added I am closing this issue
