### ISSUE TITLE
[CLOSED Orthorobot/robot

### ISSUE THREAD

**Issue by IsaacMvmv** [piware14/pi-ware#28]
Is this app installable with `sudo apt install`?
nO
If you've created a zip file for this app, upload it here.
Maybe:
[robot.zip](https://github.com/zachthecoder14/pi-ware/files/6555319/robot.zip)

**Comment by ZaydTheCoder** [comment]
This has been open for a long time, did testing succeed? Is it ready for pi-ware or does it need edits?

**Comment by Painadath** [comment]
@ZaydTheCoder I have tried it but not the install script

**Comment by ZaydTheCoder** [comment]
If it works and there is a install and uninstall then it can be added. Let me look at the code. @IsaacMvmv is this an old zip or is tis the latest?

**Comment by Painadath** [comment]
I think latest just try it @ZaydTheCoder

**Comment by ZaydTheCoder** [comment]
The repo for this is at: https://github.com/IsaacMvmv/Robot_rpi/tree/main (correct me if this is wrong @IsaacMvmv)

**Comment by ZaydTheCoder** [comment]
@IsaacMvmv I have tested orthorobot, there are some errors with the code. I will make a PR to your repo and i will make a working install script so the users only have to run one command

**Comment by oxmc** [comment]
This app has been added, closing this issue.
