### ISSUE TITLE
CryApp

### ISSUE THREAD

**Issue by RP400** [piware14/pi-ware#29]
Is this app installable with `sudo apt install`?
No its not
If you've created a zip file for this app, upload it here.
[CryApp.zip](https://github.com/zachthecoder14/pi-ware/files/6575651/CryApp.zip)

**Comment by oxmc** [comment]
Thank you @RP400 For creating a app request! We will test your app and see if we can add it to pi-ware!

**Comment by oxmc** [comment]
@RP400 Please upload the new .zip.

**Comment by RP400** [comment]
> @RP400 Please upload the new .zip.

Its in /Pi-Ware/CryApp.zip in my repo

**Comment by oxmc** [comment]
This app has been added to pi-ware, I am now closing this issue.

**Comment by ghost** [comment]
Hey, does this work with regular MCPI? I’m not sure if you’re aware, but MCPI-Revival is shutting down because they weren’t approved by Mojang.

**Comment by oxmc** [comment]
> Hey, does this work with regular MCPI? I’m not sure if you’re aware, but MCPI-Revival is shutting down because they weren’t approved by Mojang.

I did not know MCPI was shutting down!

**Comment by RP400** [comment]
> Hey, does this work with regular MCPI? I’m not sure if you’re aware, but MCPI-Revival is shutting down because they weren’t approved by Mojang.

yes it does

**Comment by NoozAbooz** [comment]
> Hey, does this work with regular MCPI? I’m not sure if you’re aware, but MCPI-Revival is shutting down because they weren’t approved by Mojang.

Mojang have not communicated with us about being "approved". We do not redistribute modified binaries which means we are all in the clear in terms of copyright infringement.

**Comment by torralbaa** [comment]
Er, we're not shutting down anytime soon, I don't know where you heard that but it's plain wrong.

**Comment by RP400** [comment]
> Er, we're not shutting down anytime soon, I don't know where you heard that but it's plain wrong.

I think continue this conversation in pi-wares discord

**Comment by oxmc** [comment]
Closing this issue as `CryApp` has already been added to pi-ware.
