### ISSUE TITLE
Banware

### ISSUE THREAD

**Issue by ghost** [piware14/pi-ware#3]
Yo Zach, your Discord client is 3rd party and thus violates their TOS. Either remove it or I'm reporting. **You have one day.**

**Comment by ghost** [comment]
Done.

**Comment by gl91306** [comment]
> Yo Zach, your Discord client is 3rd party and thus violates their TOS. Either remove it or I'm reporting. **You have one day.**

and what about pi-apps discord client?

**Comment by ghost** [comment]
> > Yo Zach, your Discord client is 3rd party and thus violates their TOS. Either remove it or I'm reporting. **You have one day.**
> 
> and what about pi-apps discord client?

It is, too.

**Comment by Painadath** [comment]
> > > Yo Zach, your Discord client is 3rd party and thus violates their TOS. Either remove it or I'm reporting. **You have one day.**
> > 
> > 
> > and what about pi-apps discord client?
> 
> It is, too.

Then why your not informing Botspot or pi apps people why us?

**Comment by gl91306** [comment]
exactly
