### ISSUE TITLE
MCPI Modded

### ISSUE THREAD

**Issue by NoozAbooz** [piware14/pi-ware#31]
Is this app installable with `sudo apt install`?
No

If you've created a zip file for this app, upload it here.
[MCPI Modded.zip](https://github.com/zachthecoder14/pi-ware/files/6585226/MCPI.Modded.zip)

**Comment by Painadath** [comment]
Thank you @mobilegmYT we will check your script and will add it to pi ware as soon as possible and also can you suggest a way to add icon + text on tkinter button thanks

**Comment by oxmc** [comment]
Add MCPI Modded to pi-ware, closing this issue.
