### ISSUE TITLE
Change terminal to terminal-run

### ISSUE THREAD

**Issue by NoozAbooz** [piware14/pi-ware#32]
This was the only template I could use since no suggestion template.

Using terminal-run will mean lxterminal wont need to be installed.
https://raw.githubusercontent.com/Botspot/pi-apps/master/etc/terminal-run

**Comment by ghost** [comment]
Hey there, could you give an example?

**Comment by NoozAbooz** [comment]
> Hey there, could you give an example?

Basically, add the terminal-run file to the pi-ware repo. Change all code that calls lxterminal to call terminal-run instead and change the formatting to comply with terminal-run's style. terminal-run will then run whatever command you send it in the terminal available on the system, eg if i dont have lxterminal but xfce-terminal installed, it will automatically run that command with xfce-terminal

**Comment by ghost** [comment]
So I can use `terminal-run -e '<command>'`?

**Comment by NoozAbooz** [comment]
> So I can use `terminal-run -e '<command>'`?

![image](https://user-images.githubusercontent.com/44128563/120863338-9b131100-c547-11eb-98c5-80b80b43d325.png)
 so like `./terminal-run "sudo apt install ee" "installing ee"`

**Comment by ghost** [comment]
Why `./`?

**Comment by NoozAbooz** [comment]
> Why `./`?

it's a file inside the repo... its not a command

**Comment by ghost** [comment]
Oh ok

**Comment by Painadath** [comment]
@mobilegmYT i think this will cause copywrite issue so if we use this we have to give credits to botspot in our readme.md which will cuase users that pi-ware depends on pi-apps

**Comment by NoozAbooz** [comment]
>  @mobilegmYT i think this will cause copywrite issue so if we use this we have to give credits to botspot in our readme.md which will cuase users that pi-ware depends on pi-apps

Pi-ware already uses so many elements from pi-apps that you might as well give credit.

**Comment by oxmc** [comment]
> > @mobilegmYT i think this will cause copywrite issue so if we use this we have to give credits to botspot in our readme.md which will cuase users that pi-ware depends on pi-apps
> 
> Pi-ware already uses so many elements from pi-apps that you might as well give credit.

What parts?

**Comment by NoozAbooz** [comment]
> > > @mobilegmYT i think this will cause copywrite issue so if we use this we have to give credits to botspot in our readme.md which will cuase users that pi-ware depends on pi-apps
> > 
> > 
> > Pi-ware already uses so many elements from pi-apps that you might as well give credit.
> 
> What parts?

Mostly I'd say it uses heavy inspiration from pi-apps for the modular design, error handling and etc. And also the only linux app that runs install scripts without a `.sh` extension is pi-apps, since it's quite unconventional.

**Comment by oxmc** [comment]
Fair enough.

**Comment by oxmc** [comment]
@mobilegmYT I have integrated terminal-run into pi-ware, add now it should work on all of the support terminals.

**Comment by oxmc** [comment]
Closing this issue.
