### ISSUE TITLE
quake 3 lite

### ISSUE THREAD

**Issue by confuzled** [piware14/pi-ware#36]
Can this app run on RPi? If so, please provide a link to a tutorial if applicable.

yes , https://pimylifeup.com/raspberry-pi-quake-3/

Is this app something many GUI users would find useful?

yes i think people would probably be intrested in downloading this

Is this app installable with sudo apt install?

no

im not sure if it would be worth adding since its only a few terminal lines however it would make it easier for people using pi as a basic desktop and are unsure of how to use the terminal

also as i dont know much about bash i can put all the commands here however i wont really be able to compile them to something that is very functional

**Comment by confuzled** [comment]
i would need help adding the bash script as well im not very good at that but apart from that here is the line of commands to install:

```
sudo apt update
sudo apt full-upgrade
sudo apt install git libasound2-dev libudev-dev libibus-1.0-dev libevdev-dev libdbus-1-dev libcurl4-openssl-dev fcitx-libs-dev libgbm-dev libsamplerate0-dev xinput
git clone https://github.com/cdev-tux/q3lite.git
cd ~/q3lite
sudo ./make-raspberrypi.sh
sudo ./make-raspberrypi.sh install
ls -l /usr/local/games/quake3/baseq3/
```

**Comment by oxmc** [comment]
@donnerkebab1730 Try reading our [wiki](https://github.com/piware14/pi-ware/wiki/Add-apps-to-pi-ware.-(Tutorial)), that should help you.

**Comment by oxmc** [comment]
If not, i can make the scripts for you.

**Comment by confuzled** [comment]
> @donnerkebab1730 Try reading our [wiki](https://github.com/piware14/pi-ware/wiki/Add-apps-to-pi-ware.-(Tutorial)), that should help you.

I tried reading the wiki but I'm a bit unsure I will read over it again though

**Comment by oxmc** [comment]
> > @donnerkebab1730 Try reading our [wiki](https://github.com/piware14/pi-ware/wiki/Add-apps-to-pi-ware.-(Tutorial)), that should help you.
> 
> I tried reading the wiki but I'm a bit unsure I will read over it again though

No problem, if you want help i can explain it to you in discord.

**Comment by ZaydTheCoder** [comment]
> i would need help adding the bash script as well im not very good at that but apart from that here is the line of commands to install:
> 
> ```
> sudo apt update
> sudo apt full-upgrade
> sudo apt install git libasound2-dev libudev-dev libibus-1.0-dev libevdev-dev libdbus-1-dev libcurl4-openssl-dev fcitx-libs-dev libgbm-dev libsamplerate0-dev xinput
> git clone https://github.com/cdev-tux/q3lite.git
> cd ~/q3lite
> sudo ./make-raspberrypi.sh
> sudo ./make-raspberrypi.sh install
> ls -l /usr/local/games/quake3/baseq3/
> ```
Not all users should run sudo apt full-upgrade. full-upgrade can remove packages that the user has installed and they will need to install the packages again. sudo apt upgrade doesn't remove packages but still upgrades the system.

**Comment by Painadath** [comment]
> > i would need help adding the bash script as well im not very good at that but apart from that here is the line of commands to install:
> > ```
> > sudo apt update
> > sudo apt full-upgrade
> > sudo apt install git libasound2-dev libudev-dev libibus-1.0-dev libevdev-dev libdbus-1-dev libcurl4-openssl-dev fcitx-libs-dev libgbm-dev libsamplerate0-dev xinput
> > git clone https://github.com/cdev-tux/q3lite.git
> > cd ~/q3lite
> > sudo ./make-raspberrypi.sh
> > sudo ./make-raspberrypi.sh install
> > ls -l /usr/local/games/quake3/baseq3/
> > ```
> 
> Not all users should run sudo apt full-upgrade. full-upgrade can remove packages that the user has installed and they will need to install the packages again. sudo apt upgrade doesn't remove packages but still upgrades the system.

@ZaydTheCoder it is not even neccessory but it is good to update

**Comment by confuzled** [comment]
oky we could remove the full update thing and replace it withe= a standard one?

**Comment by Painadath** [comment]
Yes

**Comment by confuzled** [comment]
Should close this tbh

**Comment by ZaydTheCoder** [comment]
@donnerkebab1730 Did you still want to add this app or should we leave it?

**Comment by confuzled** [comment]
Wasn't full functional do I decided to leave it

**Comment by ZaydTheCoder** [comment]
Oh ok. Another issue sorted
