### ISSUE TITLE
Rayman 2 in pi-ware

### ISSUE THREAD

**Issue by IsaacMvmv** [piware14/pi-ware#39]
Is this app installable with `sudo apt install`?
Hoping yes, but no
An app must have 4 core files to be added to pi-ware,
- ``description.txt``
- ``install``
- ``uninstall``
- ``icon.png``

OK

A tutorial on adding an app is availible on our <a href="https://github.com/zachthecoder14/pi-ware/wiki/Add-apps-to-pi-ware.-(Tutorial)">wiki</a>

If you've created a zip file for this app, upload it here.
Ok
Anything else we should know?

The engine is open source, I haven't tested it yet, but it may work. I think game is paid, and you have to have the copy

Its rayman 2!!!

And in archive.org  exists a legal copy of the game 
:D

No shop has discovered this before

What do u think

**Comment by oxmc** [comment]
Interesting, What is the purpose of adding this app?

**Comment by IsaacMvmv** [comment]
Game, play, gaming

**Comment by oxmc** [comment]
ok, Is this app available for armhf?

**Comment by IsaacMvmv** [comment]
Engine is open source, so it may be

**Comment by oxmc** [comment]
ok

**Comment by ZaydTheCoder** [comment]
Should we take note of the fact that it is paid or should we leave it? We would have to add on the description that the app is paid. Users may be disappointed if they find that they have to pay for it.

**Comment by gl91306** [comment]
I dont think paid apps should be in pi-ware until we find a system to check if a user has paid

**Comment by oxmc** [comment]
Ok, closing this issue then.
