### ISSUE TITLE
Add MultiMC to PiWare

### ISSUE THREAD

**Issue by ghost** [piware14/pi-ware#41]
wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
add "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main" to /etc/apt/sources.list
sudo apt update
sudo apt install qtbase5-dev cmake adoptopenjdk-14-hotspot clang

mkdir build
mkdir install
git clone --recursive https://github.com/MultiMC/MultiMC5.git src

change src/libraries/launcher/CMakeLists.txt and src/libraries/javacheck/CMakeLists.txt to 1.7 instead of 1.6

cd build
cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang ../src
make -j4
GitHub

**Comment by ZaydTheCoder** [comment]
Ok, do you have an uninstall script for MultiMC? You also need a description for us to add this app. You can also add an optional icon in .png format.

**Comment by ghost** [comment]
https://github.com/JJTech0130/MultiMC5/releases

The Arm64 version that has active support

**Comment by ghost** [comment]
I am not sure how to uninstall any of them

**Comment by ghost** [comment]
https://github.com/comp500/MultiMCPi

Is where the port comes from

**Comment by ZaydTheCoder** [comment]
> I am not sure how to uninstall any of them

You will need to find or make a script that uninstalls MultiMC. It is a requirement for uploading an app to pi-ware.

**Comment by ghost** [comment]
I think it is just delete the multimc folder

**Comment by ZaydTheCoder** [comment]
No, I wouldn't guess it is that simple. It would have to reverse everything the install did so the user's OS is the same as when the didn't have MultiMC.

**Comment by oxmc** [comment]
> Ok, do you have an uninstall script for MultiMC? You also need a description for us to add this app. You can also add an optional icon in .png format.

a icon.png file is required.

**Comment by ZaydTheCoder** [comment]
Oh yeah, I forgot we made it a necessity when adding an app.

**Comment by IsaacMvmv** [comment]
Hehehe

Only works on arm64/aarch64

Just we need a GOOD RECENT NEW compilation for ARM, thing im trying with pain xd

**Comment by oxmc** [comment]
@IsaacMvmv I am going to close this until you respond.
