### ISSUE TITLE
Userland architecture not detected correctly

### ISSUE THREAD

**Issue by NoozAbooz** [piware14/pi-ware#45]
I couldn't find an issue template for bug requests so suggestion it is.

Currently, pi-ware detects architecture from kernel arch, not userland. Even if I'm running a 64-bit kernel and 32-bit userland it still detects me as 64-bit which breaks apps.
![image](https://user-images.githubusercontent.com/44128563/126588346-121784a1-7b3e-46d4-943a-0c4fbc0997e3.png)

To fix it just replace it with this code which detects userland arch. You'll need to port it to python though.
```
if [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 64)" ];then
  MACHINE='aarch64'
elif [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 32)" ];then
  MACHINE='armv7l'
fi
```

**Comment by oxmc** [comment]
Why do we need to port it to python? @mobilegmYT

**Comment by ZaydTheCoder** [comment]
I think he means that he thinks we use python scripts for install and uninstall like we used to @oxmc . Rest assured @mobilegmYT , we use shell scripts for our install, uninstall. This does not need to be ported to python.

**Comment by Jai-JAP** [comment]
We can also fix it by replacing 
https://github.com/piware14/pi-ware/blob/4aaf3d036b4a967acaac4d508f578caa3b346447/install#L64-L71
by 
```
 if [ "$(dpkg --print-architecture)" == "armhf" ]; then 
   echo "Your aarch type is: armv7l" 
   echo armv7l > $HOME/.local/share/pi-ware/arch 
elif [ "$(dpkg --print-architecture)" == "arm64" ]; then 
   echo "Your aarch type is: aarch64"
   echo aarch64 > $HOME/.local/share/pi-ware/arch 
 else 
   warning "2" "Unable to detect arch type! Continuing install..." 
 fi 

```

in pi-ware/install

**Comment by NoozAbooz** [comment]
> I think he means that he thinks we use python scripts for install and uninstall like we used to @oxmc . Rest assured @mobilegmYT , we use shell scripts for our install, uninstall. This does not need to be ported to python.

Oh lol, I thought everything was written in python but looks like only main app is.

**Comment by ZaydTheCoder** [comment]
So lol

**Comment by leha-code** [comment]
😆

**Comment by leha-code** [comment]
Hez idiot

**Comment by leha-code** [comment]
Doesn't look at the code lmao
