### ISSUE TITLE
doom (original)

### ISSUE THREAD

**Issue by confuzled** [piware14/pi-ware#47]
Is this app installable with `sudo apt install`?

yes but only for the first command the rest you need to do without sudo apt install

im gonna need help with the uninstall as i have no idea how to do it, plus my bash scripting ability is next to none but i will try.

the install commands are:
`sudo apt install chocolate-doom`

`sudo wget http://www.doomworld.com/3ddownloads/ports/shareware_doom_iwad.zip`

`sudo unzip shareware_doom_iwad.zip`

`chocolate-doom-setup`

after those commands are entered it should bring you to the configuration then youll be done installing and can play

Anything else we should know?

this isnt the doom on pi apps this is different

**Comment by confuzled** [comment]
https://www.makeuseof.com/tag/run-doom-raspberry-pi/ is the tutorial

**Comment by confuzled** [comment]
if you want the bad bash script i have wrote ping me on discord as it wont let me upload the file here:(

**Comment by oxmc** [comment]
@donnerkebab1730 What we mean by: "Is this app installable with ``sudo apt install``?", we mean, can this app be installed by apt, like: ``sudo apt install doom-og``

**Comment by ZaydTheCoder** [comment]
Wait, if doom can be installed like that, we can't add it. Unless it's an updated version.

**Comment by oxmc** [comment]
True, but so is Mari0

**Comment by ZaydTheCoder** [comment]
So, Mari0 is available on apt?

**Comment by ZaydTheCoder** [comment]
Or is it that it would take a lot of commands to compile mari0

**Comment by oxmc** [comment]
I think an old version is availible on pacman
not apt

**Comment by ZaydTheCoder** [comment]
We will add an apt app if it is a newer version. Otherwise, your app will be declined.

**Comment by ZaydTheCoder** [comment]
Same for other package managers

**Comment by confuzled** [comment]
> @donnerkebab1730 What we mean by: "Is this app installable with ``sudo apt install``?", we mean, can this app be installed by apt, like: ``sudo apt install doom-og``

K

**Comment by confuzled** [comment]
> Wait, if doom can be installed like that, we can't add it. Unless it's an updated version.

it is sorta an updated version

**Comment by confuzled** [comment]
as in it has better server features and a config menu

**Comment by ZaydTheCoder** [comment]
Yeah, we can still add this. @donnerkebab1730 I need a thicker description than Original Doom, Published by Id software. After that, doom can be tested and uploaded to github.

**Comment by oxmc** [comment]
@donnerkebab1730 Do you want me to make a script for you?

**Comment by confuzled** [comment]
> Yeah, we can still add this. @donnerkebab1730 I need a thicker description than Original Doom, Published by Id software. After that, doom can be tested and uploaded to github.

Sounds good I'll work on that as I need to go just now

**Comment by confuzled** [comment]
> @donnerkebab1730 Do you want me to make a script for you?

I think mr anonymous was working on it in discord somewhere might be in no mic

**Comment by ZaydTheCoder** [comment]
> @donnerkebab1730 Do you want me to make a script for you?

Yeah @oxmc , I already have the scripts, only apt compatible. I'm just waiting for a description from donnerkebab1730. Oxmc, can you also find that downscaled image of the doom logo? You know the one in the discord.

**Comment by confuzled** [comment]
The doom demo, published by I'd software. The first part of the 3 floppy disks

**Comment by ZaydTheCoder** [comment]
Still sounding pretty short, maybe a description of what happens in the game. e.g: worthorians have taken over our spaceship, find the other crew members in hiding and defeat the worthorians once and for all.

**Comment by confuzled** [comment]
> Still sounding pretty short, maybe a description of what happens in the game. e.g: worthorians have taken over our spaceship, find the other crew members in hiding and defeat the worthorians once and for all. 

The invasion from hell has begun, you the doom slayer are tasked with killing off the demons that have appeared.

**Comment by ZaydTheCoder** [comment]
Yes, that's good.

**Comment by ZaydTheCoder** [comment]
I'll send the doom installer in the testing channel.

**Comment by ZaydTheCoder** [comment]
We are closing this issue, Doom is supposedly working.

**Comment by confuzled** [comment]
:D
