### ISSUE TITLE
I dont know how to contact you but, 

### ISSUE THREAD

**Issue by JosephYapYEEEEEEEEEEEEEEEEEEEEEEEEEEEET** [piware14/pi-ware#48]
ill make a fork on the mrcrayfish device mod with a custom gitweb

**Comment by ZaydTheCoder** [comment]
@JosephYapYEEEEEEEEEEEEEEEEEEEEEEEEEEEET what are you asking for? you want to add an app?

**Comment by ZaydTheCoder** [comment]
If you want to contact us, join us on discord at https://dsc.gg/pi-ware

**Comment by JosephYapYEEEEEEEEEEEEEEEEEEEEEEEEEEEET** [comment]
you left a comment on mrcrayfish's gitweb site, i just dont know how to reply to that since its archived

**Comment by ZaydTheCoder** [comment]
I don't know what website is Mr.Crayfish's website but I don't think we have anything to do with it.

**Comment by oxmc** [comment]
@JosephYapYEEEEEE , I have already made a fork of the mod.

**Comment by oxmc** [comment]
It's available here: https://github.com/oxmc/MrCrayfishDeviceMod

**Comment by ZaydTheCoder** [comment]
This doesn't have anything to do with pi-ware, please keep this between members.
