### ISSUE TITLE
Mineshaft Preview

### ISSUE THREAD

**Issue by leha-code** [piware14/pi-ware#56]
Is this app installable with `sudo apt install`?
No
An app must have 4 core files to be added to pi-ware,
- ``description.txt``
- ``install``
- ``uninstall``
- ``icon.png``

A tutorial on adding an app is availible on our <a href="https://github.com/zachthecoder14/pi-ware/wiki/Add-apps-to-pi-ware.-(Tutorial)">wiki</a>

If you've created a zip file for this app, upload it here.
[z.zip](https://github.com/piware14/pi-ware/files/7655851/z.zip)

Anything else we should know?
The zip was created for pi-apps, you will need to modify it to work with pi-ware. Install and uninstall scripts work everywhere

**Comment by IsaacMvmv** [comment]
Staff (Cof cof @oxmc ) Dont want to add piapps apps in piware

:c

**Comment by leha-code** [comment]
It is not in pi-apps
[mspreview.zip](https://github.com/piware14/pi-ware/files/7656826/mspreview.zip) only in pi-apps-x86

**Comment by gl91306** [comment]
okie ye then its fine

**Comment by oxmc** [comment]
@leha-code i'll review this later, atm i have to work on something, but i will keep you updated.

**Comment by oxmc** [comment]
> Staff (Cof cof @oxmc ) Dont want to add piapps apps in piware
> 
> :c

Um, no, i am fine with that, if someone requests it in pi-ware, let them have the app, us adding apps from pi-apps to pi-ware just by copying files, is what i dont want.

**Comment by oxmc** [comment]
@leha-code Do you still want to add this app?

**Comment by leha-code** [comment]
No
