### ISSUE TITLE
Deltarune Chapter 1 Returns a GML Error

### ISSUE THREAD

**Issue by jjamjam** [piware14/pi-ware#57]
**What's your pi-ware version? (run ``cat $HOME/.local/share/pi-ware/version``)**

Pi-Ware Version: 1fb499ee2abb748c493c43a08b081a9a48e972e8

**What's the bug you are experiencing?**

Deltarune Chapter 1+2 runs fine but choosing 'Yes' to 'Would you like to start from Chapter 1?'

**How can we contact you?**

Email: jamtron9000@gmail.com

ERROR in
action number 1
of Create Event
for object obj_initializer2_ch1:
ds_map_size argument 1 incorrect type (undefined)...

**Comment by gl91306** [comment]
update and re-install, it should work

**Comment by gl91306** [comment]
lol i forgot to include the laguage file for chapter 1, and that was it

**Comment by jjamjam** [comment]
Awesome.
