### ISSUE TITLE
Krunker For Pi

### ISSUE THREAD

**Issue by 220735540** [piware14/pi-ware#58]
Is this app installable with `sudo apt install`?
No
An app must have 4 core files to be added to pi-ware,
- ``description.txt``
- ``install``
- ``uninstall``
- ``icon.png``
Has all 4 (plus an extra for dependencies - the dependencies are no longer required)
The files are here located here:
https://github.com/220735540/Krunker-RaspberryPi/tree/main/Pi-Ware%20Install%20Data

**Comment by oxmc** [comment]
@220735540 Thanks for submitting an app!

Please ensure your app does work with pi-ware, and it detects it.

**Comment by 220735540** [comment]
kk. Ill test now.

**Comment by 220735540** [comment]
Ok it works, and detects it. 
New data is here:
https://github.com/220735540/Krunker-RaspberryPi/tree/main/Pi-Ware%20Install%20Data

**Comment by oxmc** [comment]
@220735540 thank you, after we test it, we'll add it.

**Comment by 220735540** [comment]
Ok, Thanks Alot.

**Comment by 220735540** [comment]
Say i needed to update the install script. How would i do that with it also updating in Pi-Ware Repo?

**Comment by oxmc** [comment]
create a pr with your changed script, then inform us and we will change it.

**Comment by 220735540** [comment]
Ok. Ive just changed the description.text.
https://github.com/220735540/Krunker-RaspberryPi/tree/main/Pi-Ware%20Install%20Data/description.txt

**Comment by 220735540** [comment]
> create a pr with your changed script, then inform us and we will change it.

My directory isnt there yet.

**Comment by 220735540** [comment]
So i just sent you the link to the change above

**Comment by 220735540** [comment]
Any Updates?

**Comment by oxmc** [comment]
@220735540 i havent had time to test today, but i'll have the testors test it.

**Comment by 220735540** [comment]
@oxmc Ok, and btw im making an app that builds webapps for you. Do you think thats something you would want to add to the store?

**Comment by 220735540** [comment]
It isnt finished yet. Im still designing the gui

**Comment by gl91306** [comment]
by app that builds webapps for you, so you mean as a standalone electron webapp, or a .desktop file that links to a website run in chromium sandbox mode

**Comment by 220735540** [comment]
> by app that builds webapps for you, so you mean as a standalone electron webapp, or a .desktop file that links to a website run in chromium sandbox mode

@gl91306 
yes its a python gui that uses cromium sandbox

**Comment by gl91306** [comment]
cool. Also I think that when u finish the app that makes webapps, you probably shouldent add krunker, because if all you need to do to create a webapp is just to add a link to ur webapp creator, then ir wouldent make sense to fill up pi-ware with chromium sandbox webapps. Also when u make the app that makes webapps, make sure that it downloads chomrium if it isnt installed

**Comment by 220735540** [comment]
ok

**Comment by 220735540** [comment]
@gl91306 @oxmc 
I have finished the WebApp Maker app all the data you need to add it to pi ware is here:
https://github.com/220735540/WebAppMaker/tree/main/Data
I've already tested it myself and it works perfectly fine.

**Comment by gl91306** [comment]
ok ill pr it

**Comment by oxmc** [comment]
@220735540 added, thank you, i will now close this issue.
