### ISSUE TITLE
Pi-Ware doesn't install

### ISSUE THREAD

**Issue by basedSkeleton** [piware14/pi-ware#61]
What's your pi-ware version? (run ``cat $HOME/.local/share/pi-ware/version``)
N/A
Pi-Ware Version: N/A

What's the bug you are experiencing?

Pi-Ware doesn't install.
I'm guessing it's because of missing dependencies, but I can't be sure as to what dependencies i need to install or extra steps i need to follow, because you didn't list them in the readme.

`bash install
install: line 4: /home/pi/pi-ware/func/api: No such file or directory
failed to source /home/pi/pi-ware/func/api
Installing pi-ware...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting tk
  Using cached https://www.piwheels.org/simple/tk/tk-0.1.0-py3-none-any.whl (3.9 kB)
Collecting screeninfo
  Using cached https://www.piwheels.org/simple/screeninfo/screeninfo-0.8-py3-none-any.whl (14 kB)
Collecting ttkthemes
  Downloading ttkthemes-3.2.2.tar.gz (891 kB)
     |████████████████████████████████| 891 kB 510 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pj3zafne/ttkthemes_0206b5aa066a4686958a83285a5da180/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pj3zafne/ttkthemes_0206b5aa066a4686958a83285a5da180/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-9_ns80i1
         cwd: /tmp/pip-install-pj3zafne/ttkthemes_0206b5aa066a4686958a83285a5da180/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pj3zafne/ttkthemes_0206b5aa066a4686958a83285a5da180/setup.py", line 7, in <module>
        from tkinter import TkVersion
    ModuleNotFoundError: No module named 'tkinter'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/fa/45/ab8ada55281af99a03bc0f8be53a502eb37ee34b94819a9ced89e8b0c12f/ttkthemes-3.2.2.tar.gz#sha256=01daed001f2ff0e4f32832a0d9ea48176c0c505203b030756bdde3bd1bcb21d2 (from https://pypi.org/simple/ttkthemes/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ttkthemes-3.2.1.tar.gz (891 kB)
     |████████████████████████████████| 891 kB 144 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pj3zafne/ttkthemes_5eb28e042cde4ffda655de5879136942/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pj3zafne/ttkthemes_5eb28e042cde4ffda655de5879136942/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-d912w8co
         cwd: /tmp/pip-install-pj3zafne/ttkthemes_5eb28e042cde4ffda655de5879136942/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pj3zafne/ttkthemes_5eb28e042cde4ffda655de5879136942/setup.py", line 7, in <module>
        from tkinter import TkVersion
    ModuleNotFoundError: No module named 'tkinter'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c8/94/111d70ed15f7b15b2a71edb6236f860ddc8e138d54a8db5a1415a9395d16/ttkthemes-3.2.1.tar.gz#sha256=45298fabfb76e09152f2bc6267331c2752d7fe310e71fbc4ba285892157758bb (from https://pypi.org/simple/ttkthemes/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ttkthemes-3.2.0.tar.gz (878 kB)
     |████████████████████████████████| 878 kB 37 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pj3zafne/ttkthemes_0a2d7d0e1f3d42db9e78a469042551d2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pj3zafne/ttkthemes_0a2d7d0e1f3d42db9e78a469042551d2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e9ndgy1h
         cwd: /tmp/pip-install-pj3zafne/ttkthemes_0a2d7d0e1f3d42db9e78a469042551d2/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pj3zafne/ttkthemes_0a2d7d0e1f3d42db9e78a469042551d2/setup.py", line 7, in <module>
        from tkinter import TkVersion
    ModuleNotFoundError: No module named 'tkinter'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/8b/22/66aa3cfa5b827779655f8ed461b6c8970ceee13160824a41c8f00dacb289/ttkthemes-3.2.0.tar.gz#sha256=c5a8f3377c2c3e9da53ed63d38dd0c015b3c8a524653be99c2f473c7057b3d69 (from https://pypi.org/simple/ttkthemes/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ttkthemes-3.1.1.tar.gz (853 kB)
     |████████████████████████████████| 853 kB 25 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pj3zafne/ttkthemes_2ad15221cfcb4610861fd27ae69b4adf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pj3zafne/ttkthemes_2ad15221cfcb4610861fd27ae69b4adf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tlz2a7i4
         cwd: /tmp/pip-install-pj3zafne/ttkthemes_2ad15221cfcb4610861fd27ae69b4adf/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pj3zafne/ttkthemes_2ad15221cfcb4610861fd27ae69b4adf/setup.py", line 7, in <module>
        from tkinter import TkVersion
    ModuleNotFoundError: No module named 'tkinter'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3c/51/b8eea7189b722453ca18179fa5f8636002b20ffabc05c80c478d2e4cd5d1/ttkthemes-3.1.1.tar.gz#sha256=711dd3e124b8bfe36c85fe5c444879d4d9b9e91e48588dea17ab8b8c0d96ea9c (from https://pypi.org/simple/ttkthemes/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ttkthemes-3.1.0.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 353 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pj3zafne/ttkthemes_26411415584e453c9c2f217a9fbab2b1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pj3zafne/ttkthemes_26411415584e453c9c2f217a9fbab2b1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-v4z_7if3
         cwd: /tmp/pip-install-pj3zafne/ttkthemes_26411415584e453c9c2f217a9fbab2b1/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pj3zafne/ttkthemes_26411415584e453c9c2f217a9fbab2b1/setup.py", line 9, in <module>
        from tkinter import TkVersion
    ModuleNotFoundError: No module named 'tkinter'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ea/57/97f208d780bfc1e9f55d6e6881ff4fcd3fd99250ee02360ec441dc136aa6/ttkthemes-3.1.0.tar.gz#sha256=dff635b3479477542f634b8ebe4cdb10eeaf6fb783c330fb38124dd20c07e40a (from https://pypi.org/simple/ttkthemes/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ttkthemes-3.0.0.tar.gz (809 kB)
     |████████████████████████████████| 809 kB 390 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pj3zafne/ttkthemes_bea6abe4be094315b2ee20b2a7281ba9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pj3zafne/ttkthemes_bea6abe4be094315b2ee20b2a7281ba9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pedgo5xp
         cwd: /tmp/pip-install-pj3zafne/ttkthemes_bea6abe4be094315b2ee20b2a7281ba9/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pj3zafne/ttkthemes_bea6abe4be094315b2ee20b2a7281ba9/setup.py", line 9, in <module>
        from tkinter import TkVersion
    ModuleNotFoundError: No module named 'tkinter'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/cc/fe/04daca77eddd9988a78ac5ea7a0b867c9edf38d1a6e38fba88aab6f8476c/ttkthemes-3.0.0.tar.gz#sha256=178dec94b4e3342b0a6f4b2adfaf40de8016ba553b6fac0845cb55f4ad443a69 (from https://pypi.org/simple/ttkthemes/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ttkthemes-2.4.0.tar.gz (757 kB)
     |████████████████████████████████| 757 kB 24 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pj3zafne/ttkthemes_fded5df5a08a454ca20884096175c3f3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pj3zafne/ttkthemes_fded5df5a08a454ca20884096175c3f3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3ih1g5kf
         cwd: /tmp/pip-install-pj3zafne/ttkthemes_fded5df5a08a454ca20884096175c3f3/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pj3zafne/ttkthemes_fded5df5a08a454ca20884096175c3f3/setup.py", line 9, in <module>
        from tkinter import TkVersion
    ModuleNotFoundError: No module named 'tkinter'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/51/8e/296da0847a1e0a1d6ecbcc4a6f81cf5155c46400701ce64d42b88dbb6929/ttkthemes-2.4.0.tar.gz#sha256=96ae59de0674d4feedc1dca60fa8a3873440d387311c90c1ca620802faad77ea (from https://pypi.org/simple/ttkthemes/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ttkthemes-2.3.0.tar.gz (759 kB)
     |████████████████████████████████| 759 kB 166 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pj3zafne/ttkthemes_8a79ca3835004d168ea50f9ff244cd50/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pj3zafne/ttkthemes_8a79ca3835004d168ea50f9ff244cd50/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-d3f1787j
         cwd: /tmp/pip-install-pj3zafne/ttkthemes_8a79ca3835004d168ea50f9ff244cd50/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pj3zafne/ttkthemes_8a79ca3835004d168ea50f9ff244cd50/setup.py", line 9, in <module>
        from tkinter import TkVersion
    ModuleNotFoundError: No module named 'tkinter'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ea/ea/6ffff3b933a19a1c371183bd0462804a769723734a82e9cd6928529bce38/ttkthemes-2.3.0.tar.gz#sha256=25a34cf1096bced33a3d8d9b8984f3cd2cdf9a0a07c25637b9738417098892d4 (from https://pypi.org/simple/ttkthemes/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ttkthemes-2.2.0.tar.gz (476 kB)
     |████████████████████████████████| 476 kB 298 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pj3zafne/ttkthemes_630eaacfe73c42d2871e146fe872c911/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pj3zafne/ttkthemes_630eaacfe73c42d2871e146fe872c911/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2vh0k61o
         cwd: /tmp/pip-install-pj3zafne/ttkthemes_630eaacfe73c42d2871e146fe872c911/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pj3zafne/ttkthemes_630eaacfe73c42d2871e146fe872c911/setup.py", line 9, in <module>
        from tkinter import TkVersion
    ModuleNotFoundError: No module named 'tkinter'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/0f/7d/1426f2b7475d086fcedb18bbce051f3710701df50394aea93acc94ee447e/ttkthemes-2.2.0.tar.gz#sha256=4bd0742485dd7352df3f2aabc214ed55c59787330abfe345bfeced98ffb5c363 (from https://pypi.org/simple/ttkthemes/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ttkthemes-2.1.0.tar.gz (456 kB)
     |████████████████████████████████| 456 kB 137 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pj3zafne/ttkthemes_93f34d5472d14d1c9546e43bde169648/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pj3zafne/ttkthemes_93f34d5472d14d1c9546e43bde169648/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_fuoe4xs
         cwd: /tmp/pip-install-pj3zafne/ttkthemes_93f34d5472d14d1c9546e43bde169648/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pj3zafne/ttkthemes_93f34d5472d14d1c9546e43bde169648/setup.py", line 9, in <module>
        from tkinter import TkVersion
    ModuleNotFoundError: No module named 'tkinter'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/23/8c/8912e07624ff62c3e8da648996ea633d439f796854bdfd1f337e13fcac84/ttkthemes-2.1.0.tar.gz#sha256=2aa020daf2885c8de974274e50347242f86965b09bac292c4f6e98a09cf7a7ed (from https://pypi.org/simple/ttkthemes/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ttkthemes-2.0.6.tar.gz (3.7 MB)
     |████████████████████████████████| 3.7 MB 355 kB/s 
Collecting pillow
  Downloading Pillow-9.1.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 120 kB/s 
Building wheels for collected packages: ttkthemes
  Building wheel for ttkthemes (setup.py) ... done
  Created wheel for ttkthemes: filename=ttkthemes-2.0.6-cp39-cp39-linux_aarch64.whl size=4014617 sha256=a903bd49ac2aa509f5b5911b74672c18a867368c124bb3b3277d99ccead8f5bb
  Stored in directory: /root/.cache/pip/wheels/7b/3c/86/4a27aa7715f397e7ff0b27f2abbb81df9d62a269e6ed1cd903
Successfully built ttkthemes
Installing collected packages: pillow, ttkthemes, tk, screeninfo
Successfully installed pillow-9.1.0 screeninfo-0.8 tk-0.1.0 ttkthemes-2.0.6
mkdir: cannot create directory ‘’: No such file or directory
mkdir: cannot create directory ‘’: No such file or directory
install: line 13: cd: /home/pi/pi-ware: No such file or directory
install: line 14: /version: Permission denied
Creating a desktop entry for Pi-Ware...
mkdir: cannot create directory ‘’: No such file or directory
install: line 19: [: : integer expression expected
install: line 32: /pi-ware.desktop: Permission denied
Creating an auto updater for Pi-Ware...
cp: cannot stat '/home/pi/pi-ware/func/term/pi-ware-term': No such file or directory
chmod: cannot access '/usr/local/bin/pi-ware': No such file or directory
Added pi-ware-commands to Terminal!
Please restart terminal to apply changes.
Your aarch type is: aarch64
install: line 81: /aarch: Permission denied
Package manager is: apt
install: line 88: /inst-pref: Permission denied
Done!
You can find Pi-Ware in Menu > Accessories > Pi-Ware.`
After this there is nothing in Menu > Accessories > Pi-Ware

How can we contact you?
Through this github issue

EMAIL OR DISCORD
N/A

**Comment by gl91306** [comment]
First of all, did you git clone pi-ware in your home directory? The first error says that it couldn't locate /home/pi/pi-ware/func/api, so i'm assuming that you git-cloned pi-ware in some other directory. Second, you said that there might be a missing dependency issue. That's true, as it says that you are missing tkinter, but the real issue is your python install, because tkinter is pre installed onto python by default (In fact it is the only framework built into python). Try re-installing python to fix this. If this issue still persists, please let us know.

**Comment by leha-code** [comment]
Actually, tkinter only comes with the "batteries included" Python distribution pack. For example, python for android (p4a) does not include all batteries, so no tkinter there. Just noted because this might be the error and tkinter isn' installable via pip

**Comment by oxmc** [comment]
@basedSkeleton How did you install pi-ware?

**Comment by gl91306** [comment]
no reply in a month, closing
