### ISSUE TITLE
nothing

### ISSUE THREAD

**Issue by oxmc** [piware14/pi-ware#62]
@gl91306 I can't access discord right now, so please inform everyone of the new update.

**Comment by gl91306** [comment]
what update

**Comment by oxmc** [comment]
The fix for pi-ware and the new apps. @gl91306

**Comment by gl91306** [comment]
okie

**Comment by gl91306** [comment]
![Screenshot 2022-04-08 9 16 26 AM](https://user-images.githubusercontent.com/75343148/162481796-9e71be3c-889f-40e4-b5bd-45d44e6557a8.png)

**Comment by oxmc** [comment]
Thanks @gl91306
