### ISSUE TITLE
Improve the GUI

### ISSUE THREAD

**Issue by Griphcode** [piware14/pi-ware#65]
What does this suggestion do to pi-ware?
Will make users love the application more!

Why should we add this?
Makes it a better and more professional app

**Comment by gl91306** [comment]
could you make a descriptor as to how we should do that? like a drawing of what an improved gui would look like.

**Comment by gl91306** [comment]
like a base for us to go off on

**Comment by Griphcode** [comment]
SURE!

**Comment by gl91306** [comment]
thanks

**Comment by Griphcode** [comment]
np

Den tis 26 juli 2022 kl 21:03 skrev gl91306 ***@***.***>:

**Comment by oxmc** [comment]
closed for now
